name: ⚙️ Build Binaries

on:
  workflow_call:

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 2.0.0

      - uses: goto-bus-stop/setup-zig@v2

      - name: Bootstrap with installed version
        run: nimble install -Y

      - name: Generate build artifacts
        run: nimble release

      - name: Create artifact bundles
        run: nimble bundle

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dist/*.tar.gz
            dist/*.zip

