name: ⚙️ Build Binaries

on:
  workflow_call:

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jiro4989/setup-nim-action@v2
      - uses: mlugg/setup-zig@v2

      - name: Bootstrap with installed version
        run: |
          nimble install -Y

      - name: Generate build artifacts
        run: |
          nimble setup -l
          nim release

      - name: Create artifact bundles
        run: nim bundle

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            dist/*.tar.gz
            dist/*.zip

