name: 🌙 Nightly Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write

jobs:
  check-commits:
    uses: daylinmorgan/actions/.github/workflows/check-commits.yml@main
    with:
      since: "24 hours"

  build-artifacts:
    needs: check-commits
    if: ${{ needs.check-commits.outputs.quit != 'true' }}
    uses: ./.github/workflows/build.yml

  generate-release:
    needs: build-artifacts
    uses: daylinmorgan/actions/.github/workflows/nightly.yml@main
