name: 🚀 Release

on:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-artifacts:
    needs: test
    uses: ./.github/workflows/build.yml

  create-release:
    needs: build-artifacts
    uses: daylinmorgan/actions/.github/workflows/release.yml@main
