name: 🚀 Release

on:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: write

jobs:
  build-artifacts:
    uses: ./.github/workflows/build.yml

  create-release:
    needs: build-artifacts
    uses: daylinmorgan/actions/.github/workflows/release.yml@main
